---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ .Release.Name }}-conf
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-conf
      containers:
        - name: web
          image: "{{ .Values.image.jitsi.repository }}:{{ .Values.image.jitsi.tag }}"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-env
          env:
            - name: DOCKER_HOST_ADDRESS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: JVB_WS_SERVER_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          resources: {}
          volumeMounts:
            - name: {{ .Release.Name }}-conf
              mountPath: /config
              subPath: web-config
            - name: {{ .Release.Name }}-conf
              mountPath: /var/spool/cron/crontabs
              subPath: crontabs
            - name: {{ .Release.Name }}-conf
              mountPath: /usr/share/jitsi-meet/transcripts
              subPath: transcripts
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
        - name: prosody
          image: "{{ .Values.image.prosody.repository }}:{{ .Values.image.prosody.tag }}"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-env
          resources: {}
          volumeMounts:
            - name: {{ .Release.Name }}-conf
              mountPath: /config
              subPath: prosody-config
            - name: {{ .Release.Name }}-conf
              mountPath: /prosody-plugins-custom
              subPath: prosody-plugins-custom
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
        - name: jicofo
          image: jitsi/jicofo:stable-7882
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-env
          resources: {}
          volumeMounts:
            - name: {{ .Release.Name }}-conf
              mountPath: /config
              subPath: jicofo-config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
        - name: jvb
          image: "{{ .Values.image.jvb.repository }}:{{ .Values.image.jvb.tag }}"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-env
          resources: {}
          volumeMounts:
            - name: {{ .Release.Name }}-conf
              mountPath: /config
              subPath: jvb-config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
