---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-conf
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.pvc.mode }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
