namespace: jitsi
domainname: testmeet.tina-steiger.com
extip: 195.192.158.70

pvc:
  mode: ReadWriteOnce
  size: 1G
image:
  jitsi:
    repository: jitsi/web
    tag: "stable-7882"
  prosody:
    repository: jitsi/prosody
    tag: "stable-7882"
  jvb:
    repository: jitsi/jvb
    tag: "stable-7882"
